### ISSUE TITLE
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected

### ISSUE THREAD

**Issue by WmnkVqztT1SFUXTq** [mhelmstetter/oplog-analyzer#6]
I recieved this exception when running:
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:539)
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
        at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
        at com.mongodb.oploganalyzer.OplogAnalyzer.writeExcel(OplogAnalyzer.java:248)
        at com.mongodb.oploganalyzer.OplogAnalyzer.main(OplogAnalyzer.java:402)
**** SHUTDOWN *****

Error should be related to 
"The org.apache.poi.util.POILogger was an abstract class until apache poi 4.0.1. Now in apache poi 4.1.0 it is an interface. You have a mix of apache poi versions running."
https://stackoverflow.com/questions/58147646/found-interface-org-apache-poi-util-poilogger-but-class-was-expected-error

**Comment by thecloudmason** [comment]
Workaround: delete the .xlsx file that gets generated in the bin folder.
